name: test

on:
  push:
    branches:
      - main

jobs:
  run:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: test
        uses: ./
        with:
          path: LICENSE.txt
          stringInput: 'true'
          booleanInput: true
          orderMapInput:
            - name: first
              number: 1
              bool: true
            - name: second
              number: 2
              bool: false
          mapInput:
            name: test
            number: 1
            bool: true
