name: test

on:
  push:
    branches:
      - main

jobs:
  run:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: test
        uses: ./
        with:
          path: LICENSE.txt
          stringInput: 'true'
          booleanInput: true
          mapString: >-
            [
              {
                "type": "feat",
                "section":"Features",
                "hidden":false
              },
              {
                "type":"fix",
                "section":"Bug Fixes",
                "hidden":false
              },
              {
                "type":"chore",
                "section":"Miscellaneous",
                "hidden":false
              }
            ]
